### ISSUE TITLE
save_dataloader.py 실행 중 오류

### ISSUE THREAD

**Issue by doyooni303** [TooTouch/Fake-News-Detection-Dataset#5]
BTS의 save_dataloader.py 실행 중 아래와 같은 오류가 나타났습니다.

확인해보니, 실제 뉴스(NonClickbait_Auto)에서 온 파일 내부에는 labeldDataInfo를 key로 갖는 부분이 없어서 나타나는 오류 같습니다.

확인부탁드립니다.

감사합니다.
![save_dataloader py 오류](https://user-images.githubusercontent.com/39008673/201459604-e1855586-d484-4ec1-8d55-4a731eecd025.PNG)

**Comment by tootouch** [comment]
NAS에서 direct_exp와 one_cycle에 있는 NonClickbait_Auto는 서로 다른 파일입니다.

정확히는 `one_cycle > NonClickbait_Auto`에는 원천데이터기 때문에 'labeledDataInfo'가 없고 `direct_exp > NoneClickbait_Auto`에는 'labeledDataInfo'가 추가된 폴더라고 보면 됩니다. 

혹시 one_cycle에서 다운받은 NonClickbait_Auto를 direct_exp에 저장한건 아닌지 확인부탁드립니다.
